import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gray-100">
          {/* Fixed Header */}
          <div className="fixed top-0 left-0 right-0 z-50">
            <Header />
          </div>

          {/* Sidebar + Main content */}
          <div className="flex min-h-screen pt-16"> {/* pt-16 = 64px */}
            <Sidebar />
            <main className="flex-1 p-4 overflow-y-auto scrollbar-hide">
              {children}
            </main>
          </div>

          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
